/**
 * 分享卡片画布组件 - 针对 html2canvas 优化的像素级复刻
 * 
 * 设计原则：
 * 1. 与 WeeklySummaryCard 保持视觉一致
 * 2. 使用 html2canvas 兼容的样式（避免复杂渐变，使用纯色）
 * 3. 完全相同的布局、间距、字体大小
 */

import React, { forwardRef } from 'react';
import type { ShareCardData } from '../types';

interface ShareCardCanvasProps {
  data: ShareCardData;
  weeklyTokenTotal?: number;
  language?: 'zh' | 'en';
}

// 翻译对象
const translations = {
  zh: {
    weeklySummary: '本周训练总结',
    aiCoachReview: 'AI教练评价',
    weekHighlights: '本周突破',
    days: '天',
    sets: '组',
    volume: '负荷',
    level: '等级',
    nextWeek: '下周建议',
    tokens: 'tokens',
    input: 'Input',
    output: 'Output',
    aiPowered: 'AI Powered',
    generatedBy: 'Generated by',
    ideal: '理想',
    moderate: '适中',
    insufficient: '不足',
    excessive: '过量',
    muscles: '训练肌肉'
  },
  en: {
    weeklySummary: 'Weekly Summary',
    aiCoachReview: 'AI Coach Review',
    weekHighlights: 'Weekly PRs',
    days: 'Days',
    sets: 'Sets',
    volume: 'Vol',
    level: 'Lvl',
    nextWeek: 'Next Week',
    tokens: 'tokens',
    input: 'Input',
    output: 'Output',
    aiPowered: 'AI Powered',
    generatedBy: 'Generated by',
    ideal: 'Ideal',
    moderate: 'Moderate',
    insufficient: 'Low',
    excessive: 'High',
    muscles: 'Muscles'
  }
};

// 肌肉名称中英文映射
const muscleNameMap: Record<string, string> = {
  '胸大肌': 'Chest',
  '胸肌': 'Chest',
  '背阔肌': 'Lats',
  '背部': 'Back',
  '三角肌': 'Delts',
  '三角肌前束': 'Front Delts',
  '三角肌中束': 'Side Delts',
  '三角肌后束': 'Rear Delts',
  '肩部': 'Shoulders',
  '肱二头肌': 'Biceps',
  '肱三头肌': 'Triceps',
  '手臂': 'Arms',
  '股四头肌': 'Quads',
  '腘绳肌': 'Hamstrings',
  '臀大肌': 'Glutes',
  '臀部': 'Glutes',
  '腿部': 'Legs',
  '核心': 'Core',
  '腹肌': 'Abs',
  '小腿': 'Calves',
  '全身': 'Full Body',
  '斜方肌': 'Traps',
  '下背部': 'Lower Back',
  '前臂': 'Forearms',
  '腹斜肌': 'Obliques'
};

// 肌肉颜色映射 - html2canvas 友好的 rgba 颜色（更暗更黑）
const muscleColors: Record<string, { bg: string; text: string; border: string }> = {
  '胸大肌': { bg: 'rgba(244,63,94,0.12)', text: '#fb7185', border: 'rgba(244,63,94,0.25)' },
  '胸肌': { bg: 'rgba(244,63,94,0.12)', text: '#fb7185', border: 'rgba(244,63,94,0.25)' },
  '背阔肌': { bg: 'rgba(59,130,246,0.12)', text: '#60a5fa', border: 'rgba(59,130,246,0.25)' },
  '背部': { bg: 'rgba(59,130,246,0.12)', text: '#60a5fa', border: 'rgba(59,130,246,0.25)' },
  '三角肌': { bg: 'rgba(6,182,212,0.12)', text: '#22d3ee', border: 'rgba(6,182,212,0.25)' },
  '肩部': { bg: 'rgba(6,182,212,0.12)', text: '#22d3ee', border: 'rgba(6,182,212,0.25)' },
  '肱二头肌': { bg: 'rgba(168,85,247,0.12)', text: '#c084fc', border: 'rgba(168,85,247,0.25)' },
  '肱三头肌': { bg: 'rgba(236,72,153,0.12)', text: '#f472b6', border: 'rgba(236,72,153,0.25)' },
  '手臂': { bg: 'rgba(168,85,247,0.12)', text: '#c084fc', border: 'rgba(168,85,247,0.25)' },
  '股四头肌': { bg: 'rgba(6,182,212,0.12)', text: '#22d3ee', border: 'rgba(6,182,212,0.25)' },
  '腘绳肌': { bg: 'rgba(20,184,166,0.12)', text: '#2dd4bf', border: 'rgba(20,184,166,0.25)' },
  '臀大肌': { bg: 'rgba(5,150,105,0.1)', text: '#10b981', border: 'rgba(5,150,105,0.2)' },
  '臀部': { bg: 'rgba(5,150,105,0.1)', text: '#10b981', border: 'rgba(5,150,105,0.2)' },
  '腿部': { bg: 'rgba(6,182,212,0.12)', text: '#22d3ee', border: 'rgba(6,182,212,0.25)' },
  '核心': { bg: 'rgba(249,115,22,0.12)', text: '#fb923c', border: 'rgba(249,115,22,0.25)' },
  '腹肌': { bg: 'rgba(249,115,22,0.12)', text: '#fb923c', border: 'rgba(249,115,22,0.25)' },
  '小腿': { bg: 'rgba(99,102,241,0.12)', text: '#818cf8', border: 'rgba(99,102,241,0.25)' },
  '全身': { bg: 'rgba(100,116,139,0.12)', text: '#94a3b8', border: 'rgba(100,116,139,0.25)' }
};

// 训练量评估配置
const volumeConfig: Record<string, { color: string; textColor: string; labelZh: string; labelEn: string }> = {
  insufficient: { color: '#fb923c', textColor: '#fb923c', labelZh: '不足', labelEn: 'Low' },
  adequate: { color: '#22d3ee', textColor: '#22d3ee', labelZh: '适中', labelEn: 'Moderate' },
  optimal: { color: '#34d399', textColor: '#34d399', labelZh: '理想', labelEn: 'Ideal' },
  excessive: { color: '#f87171', textColor: '#f87171', labelZh: '过量', labelEn: 'High' }
};

// 获取肌肉英文名称
const getMuscleNameEn = (muscle: string): string => {
  return muscleNameMap[muscle] || muscle;
};

// 获取肌肉标签样式
const getMuscleStyle = (muscle: string) => {
  if (muscleColors[muscle]) return muscleColors[muscle];
  for (const [key, style] of Object.entries(muscleColors)) {
    if (muscle.includes(key) || key.includes(muscle.replace(/肌$/, ''))) {
      return style;
    }
  }
  return { bg: '#14532d', text: '#34d399', border: '#166534' };
};

// 解析肌肉名称（从亮点中提取）
const extractMusclesFromHighlights = (highlights: Array<{ label: string; value: string }>): string[] => {
  const muscles: string[] = [];
  const muscleKeywords = Object.keys(muscleColors);
  
  highlights.forEach(highlight => {
    muscleKeywords.forEach(keyword => {
      if (highlight.label.includes(keyword) && !muscles.includes(keyword)) {
        muscles.push(keyword);
      }
    });
  });
  
  return muscles.slice(0, 4);
};

// 解析 highlight label
const parseHighlightLabel = (label: string): { exerciseName: string; metricType: string } => {
  const match = label.match(/^(.+?)\s+(最大重量|Max Weight|总容量|Total Vol|增长|Increase|提升|Gain|频率|Freq)$/);
  if (match) {
    return { exerciseName: match[1], metricType: match[2] };
  }
  return { exerciseName: label, metricType: '' };
};

// 格式化负荷
const formatVolume = (volume: number): string => {
  if (volume === 0) return '-';
  if (volume >= 1000000) return `${(volume / 1000000).toFixed(2)}kt`;
  if (volume >= 1000) return `${(volume / 1000).toFixed(1)}t`;
  return `${volume}kg`;
};

// SVG 图标组件
const BrainIcon = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#34d399" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96.44 2.5 2.5 0 0 1-2.96-3.08 3 3 0 0 1-.34-5.58 2.5 2.5 0 0 1 1.32-4.24 2.5 2.5 0 0 1 4.44-1.04Z"/>
    <path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96.44 2.5 2.5 0 0 0 2.96-3.08 3 3 0 0 0 .34-5.58 2.5 2.5 0 0 0-1.32-4.24 2.5 2.5 0 0 0-4.44-1.04Z"/>
  </svg>
);

const TrophyIcon = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#34d399" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M8 21h8M12 17v4"/>
    <path d="M7 4h10v5a5 5 0 0 1-10 0V4z"/>
    <path d="M7 4H5a2 2 0 0 0-2 2v1a3 3 0 0 0 3 3h1M17 4h2a2 2 0 0 1 2 2v1a3 3 0 0 1-3 3h-1"/>
  </svg>
);

const AwardIcon = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#34d399" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="12" cy="8" r="6"/>
    <path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11"/>
  </svg>
);

const CalendarIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#60a5fa" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <rect x="3" y="4" width="18" height="18" rx="2" ry="2"/>
    <line x1="16" y1="2" x2="16" y2="6"/>
    <line x1="8" y1="2" x2="8" y2="6"/>
    <line x1="3" y1="10" x2="21" y2="10"/>
  </svg>
);

const DumbbellIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#34d399" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="m6.5 6.5 11 11"/>
    <path d="m21 21-1-1"/>
    <path d="m3 3 1 1"/>
    <path d="m18 22 4-4"/>
    <path d="m2 6 4-4"/>
    <path d="m3 10 7-7"/>
    <path d="m14 21 7-7"/>
  </svg>
);

const ZapIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#22d3ee" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <polygon points="13 2 3 14 12 14 11 22 21 10 12 10"/>
  </svg>
);

const TrendingUpIcon = ({ color }: { color: string }) => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/>
    <polyline points="17 6 23 6 23 12"/>
  </svg>
);

const TargetIcon = () => (
  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#64748b" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="12" cy="12" r="10"/>
    <circle cx="12" cy="12" r="6"/>
    <circle cx="12" cy="12" r="2"/>
  </svg>
);

const SparklesIcon = ({ color = '#60a5fa' }: { color?: string }) => (
  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"/>
  </svg>
);

const CpuIcon = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#34d399" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <rect x="4" y="4" width="16" height="16" rx="2"/>
    <rect x="9" y="9" width="6" height="6"/>
    <path d="M9 1v3M15 1v3M9 20v3M15 20v3M20 9h3M20 14h3M1 9h3M1 14h3"/>
  </svg>
);

const ChevronRightIcon = () => (
  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#64748b" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <polyline points="9 18 15 12 9 6"/>
  </svg>
);

export const ShareCardCanvas = forwardRef<HTMLDivElement, ShareCardCanvasProps>(
  ({ data, weeklyTokenTotal, language = 'zh' }, ref) => {
    const t = translations[language];
    const tokenCount = weeklyTokenTotal ?? data.tokenUsage?.total_tokens ?? 0;
    
    const stats = {
      days: data.workoutDays ?? 0,
      sets: data.totalSets ?? 0,
      volume: data.totalVolume ?? 0,
      level: data.volumeLevel || 'adequate'
    };
    
    const volume = volumeConfig[stats.level] || volumeConfig.adequate;
    const period = data.dateRange || '';
    const overview = data.overview || '';
    
    // 处理 highlights
    const highlights = (data.highlights || []).slice(0, 5);
    const trainedMuscles = extractMusclesFromHighlights(highlights);
    const nextWeekMuscles = data.nextWeekRecommendations || [];

    // 分割 highlights 为两行
    const firstRow = highlights.length === 1 ? highlights.slice(0, 1) : highlights.slice(0, 2);
    const secondRow = highlights.length === 1 ? [] : highlights.slice(2, 5);

    return (
      <div 
        ref={ref} 
        style={{
          width: '360px',
          backgroundColor: '#0f172a',
          borderRadius: '16px',
          border: '1px solid #1e293b',
          overflow: 'hidden',
          fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
          color: '#f8fafc'
        }}
      >
        {/* Header */}
        <div style={{
          padding: '12px 16px',
          borderBottom: '1px solid rgba(30, 41, 59, 0.5)',
          display: 'flex',
          alignItems: 'center',
          gap: '10px'
        }}>
          <div style={{
            width: '36px',
            height: '36px',
            borderRadius: '12px',
            backgroundColor: 'rgba(16,185,129,0.15)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            border: '1px solid rgba(16,185,129,0.25)'
          }}>
            <BrainIcon />
          </div>
          <div style={{ flex: 1 }}>
            <h3 style={{ color: '#fff', fontWeight: 700, fontSize: '15px', margin: 0, lineHeight: 1.2 }}>
              {t.weeklySummary}
            </h3>
            <p style={{ color: '#64748b', fontSize: '12px', margin: '2px 0 0 0', lineHeight: 1.2 }}>{period}</p>
          </div>
        </div>

        {/* Content */}
        <div style={{ padding: '16px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          
          {/* AI评价 - 使用纯色背景替代渐变 */}
          {overview && (
            <div style={{
              position: 'relative',
              overflow: 'hidden',
              borderRadius: '12px',
              backgroundColor: 'rgba(16,185,129,0.08)',
              border: '1px solid rgba(16,185,129,0.2)',
              padding: '12px'
            }}>
              {/* 装饰性光晕 */}
              <div style={{
                position: 'absolute',
                top: '-16px',
                right: '-16px',
                width: '64px',
                height: '64px',
                borderRadius: '50%',
                backgroundColor: 'rgba(16,185,129,0.1)',
                opacity: 0.5
              }} />
              
              <div style={{ position: 'relative', display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
                <div style={{
                  width: '36px',
                  height: '36px',
                  borderRadius: '12px',
                  backgroundColor: 'rgba(16,185,129,0.15)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  flexShrink: 0,
                  border: '1px solid rgba(16,185,129,0.2)'
                }}>
                  <AwardIcon />
                </div>
                <div style={{ flex: 1, paddingTop: '2px' }}>
                  <p style={{ 
                    color: '#34d399',
                    fontSize: '12px', 
                    fontWeight: 600, 
                    margin: '0 0 4px 0',
                    lineHeight: 1.2
                  }}>
                    {t.aiCoachReview}
                  </p>
                  <p style={{ 
                    color: '#e2e8f0',
                    fontSize: '14px', 
                    lineHeight: 1.6, 
                    margin: 0 
                  }}>
                    {overview}
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* 本周突破 - 黑绿色渐变到背景，更 subtle */}
          {highlights.length > 0 && (
            <div style={{
              background: 'linear-gradient(180deg, rgba(16,185,129,0.08) 0%, rgba(15,23,42,0.5) 100%)',
              borderRadius: '16px',
              padding: '16px',
              border: '1px solid rgba(16,185,129,0.15)'
            }}>
              {/* 标题 */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px' }}>
                <div style={{
                  width: '32px',
                  height: '32px',
                  borderRadius: '10px',
                  backgroundColor: 'rgba(16,185,129,0.2)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  border: '1px solid rgba(16,185,129,0.3)'
                }}>
                  <TrophyIcon />
                </div>
                <span style={{ 
                  color: '#34d399', 
                  fontSize: '14px', 
                  fontWeight: 700,
                  lineHeight: 1.2
                }}>
                  {t.weekHighlights}
                </span>
              </div>
              
              {/* 第一行 */}
              <div style={{
                display: 'grid',
                gridTemplateColumns: firstRow.length === 1 ? '1fr' : '1fr 1fr',
                gap: '12px',
                marginBottom: '12px'
              }}>
                {firstRow.map((highlight, idx) => {
                  const { exerciseName, metricType } = parseHighlightLabel(highlight.label);
                  return (
                    <div
                      key={idx}
                      style={{
                        backgroundColor: '#020617',
                        borderRadius: '12px',
                        padding: '12px',
                        display: 'flex',
                        flexDirection: 'column',
                        justifyContent: 'space-between',
                        minHeight: '80px'
                      }}
                    >
                      <span style={{
                        fontSize: '11px',
                        color: '#cbd5e1',
                        fontWeight: 500,
                        lineHeight: 1.35,
                        wordWrap: 'break-word'
                      }}>
                        {exerciseName}
                      </span>
                      <div style={{ display: 'flex', alignItems: 'baseline', gap: '4px', marginTop: '4px' }}>
                        <span style={{ fontSize: '20px', fontWeight: 700, color: '#34d399' }}>
                          {highlight.value}
                        </span>
                        {metricType && (
                          <span style={{ fontSize: '10px', color: '#64748b' }}>{metricType}</span>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
              
              {/* 第二行 */}
              {secondRow.length > 0 && (
                <div style={{
                  display: 'grid',
                  gridTemplateColumns: firstRow.length === 1 ? '1fr' : '1fr 1fr',
                  gap: '12px'
                }}>
                  {secondRow.map((highlight, idx) => {
                    const { exerciseName, metricType } = parseHighlightLabel(highlight.label);
                    return (
                      <div
                        key={idx + 2}
                        style={{
                          backgroundColor: '#020617',
                          borderRadius: '12px',
                          padding: '10px',
                          display: 'flex',
                          flexDirection: 'column',
                          justifyContent: 'space-between',
                          minHeight: '70px'
                        }}
                      >
                        <span style={{
                          fontSize: '10px',
                          color: '#cbd5e1',
                          fontWeight: 500,
                          lineHeight: 1.3,
                          wordWrap: 'break-word'
                        }}>
                          {exerciseName}
                        </span>
                        <div style={{ display: 'flex', alignItems: 'baseline', gap: '2px', marginTop: '4px' }}>
                          <span style={{ fontSize: '16px', fontWeight: 700, color: '#34d399' }}>
                            {highlight.value}
                          </span>
                          {metricType && (
                            <span style={{ fontSize: '9px', color: '#64748b' }}>{metricType}</span>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          )}

          {/* 核心数据 */}
          <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: '8px',
            backgroundColor: 'rgba(30, 41, 59, 0.3)',
            borderRadius: '12px',
            padding: '12px'
          }}>
            {/* 天数 */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flex: 1, justifyContent: 'center' }}>
              <CalendarIcon />
              <div>
                <div style={{ fontSize: '18px', fontWeight: 700, color: '#fff', lineHeight: 1 }}>{stats.days}</div>
                <div style={{ fontSize: '10px', color: '#64748b', marginTop: '2px' }}>{t.days}</div>
              </div>
            </div>
            <div style={{ width: '1px', height: '32px', backgroundColor: '#334155' }} />
            
            {/* 组数 */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flex: 1, justifyContent: 'center' }}>
              <DumbbellIcon />
              <div>
                <div style={{ fontSize: '18px', fontWeight: 700, color: '#fff', lineHeight: 1 }}>{stats.sets}</div>
                <div style={{ fontSize: '10px', color: '#64748b', marginTop: '2px' }}>{t.sets}</div>
              </div>
            </div>
            <div style={{ width: '1px', height: '32px', backgroundColor: '#334155' }} />
            
            {/* 负荷 */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flex: 1, justifyContent: 'center' }}>
              <ZapIcon />
              <div>
                <div style={{ fontSize: '16px', fontWeight: 700, color: '#fff', lineHeight: 1 }}>
                  {formatVolume(stats.volume)}
                </div>
                <div style={{ fontSize: '10px', color: '#64748b', marginTop: '2px' }}>{t.volume}</div>
              </div>
            </div>
            <div style={{ width: '1px', height: '32px', backgroundColor: '#334155' }} />
            
            {/* 等级 */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flex: 1, justifyContent: 'center' }}>
              <TrendingUpIcon color={volume.color} />
              <div>
                <div style={{ fontSize: '16px', fontWeight: 700, color: volume.textColor, lineHeight: 1 }}>
                  {language === 'zh' ? volume.labelZh : volume.labelEn}
                </div>
                <div style={{ fontSize: '10px', color: '#64748b', marginTop: '2px' }}>{t.level}</div>
              </div>
            </div>
          </div>

          {/* 训练肌肉 */}
          {trainedMuscles.length > 0 && (
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '8px' }}>
                <TargetIcon />
                <span style={{ fontSize: '12px', color: '#64748b' }}>{t.muscles}</span>
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
                {trainedMuscles.map((muscle, idx) => {
                  const style = getMuscleStyle(muscle);
                  return (
                    <span
                      key={idx}
                      style={{
                        padding: '6px 12px',
                        borderRadius: '8px',
                        fontSize: '12px',
                        fontWeight: 500,
                        backgroundColor: style.bg,
                        color: style.text,
                        border: `1px solid ${style.border}`,
                        display: 'inline-block'
                      }}
                    >
                      {language === 'zh' ? muscle : getMuscleNameEn(muscle)}
                    </span>
                  );
                })}
              </div>
            </div>
          )}

          {/* 下周建议 */}
          {nextWeekMuscles.length > 0 && (
            <div style={{
              backgroundColor: 'rgba(59,130,246,0.08)',
              borderRadius: '12px',
              padding: '12px',
              border: '1px solid rgba(59,130,246,0.2)'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '8px' }}>
                <SparklesIcon color="#60a5fa" />
                <span style={{ fontSize: '12px', color: '#60a5fa', fontWeight: 600 }}>{t.nextWeek}</span>
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
                {nextWeekMuscles.slice(0, 3).map((muscle, idx) => {
                  const style = getMuscleStyle(muscle);
                  return (
                    <span
                      key={idx}
                      style={{
                        padding: '4px 10px',
                        borderRadius: '6px',
                        fontSize: '11px',
                        backgroundColor: style.bg,
                        color: style.text,
                        border: `1px solid ${style.border}`,
                        display: 'inline-block'
                      }}
                    >
                      {language === 'zh' ? muscle : getMuscleNameEn(muscle)}
                    </span>
                  );
                })}
              </div>
            </div>
          )}

          {/* Token统计 */}
          {tokenCount > 0 && (
            <div style={{
              position: 'relative',
              overflow: 'hidden',
              borderRadius: '12px',
              border: '1px solid rgba(16,185,129,0.2)',
              backgroundColor: 'rgba(16,185,129,0.06)'
            }}>
              <div style={{
                position: 'absolute',
                top: 0,
                right: 0,
                width: '96px',
                height: '96px',
                backgroundColor: 'rgba(16,185,129,0.05)',
                borderRadius: '50%',
                opacity: 0.5
              }} />
              
              <div style={{ position: 'relative', padding: '12px 16px' }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <div style={{
                      padding: '6px',
                      borderRadius: '8px',
                      backgroundColor: 'rgba(16,185,129,0.1)',
                      border: '1px solid rgba(16,185,129,0.15)'
                    }}>
                      <CpuIcon />
                    </div>
                    <div>
                      <div style={{ display: 'flex', alignItems: 'baseline', gap: '4px' }}>
                        <span style={{ fontSize: '16px', fontWeight: 700, color: '#fff' }}>
                          {tokenCount.toLocaleString()}
                        </span>
                        <span style={{ fontSize: '12px', color: '#64748b' }}>{t.tokens}</span>
                      </div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '10px', color: '#64748b', marginTop: '2px' }}>
                        <span>{t.input}: {((data.tokenUsage?.prompt_tokens || 0) / 1000).toFixed(1)}k</span>
                        <span style={{ opacity: 0.5 }}>•</span>
                        <span>{t.output}: {((data.tokenUsage?.completion_tokens || 0) / 1000).toFixed(1)}k</span>
                      </div>
                    </div>
                  </div>
                  
                  <div style={{ textAlign: 'right' }}>
                    {data.estimatedCost && data.estimatedCost.totalCost > 0 ? (
                      <div style={{ fontSize: '18px', fontWeight: 700, color: '#34d399' }}>
                        ¥{data.estimatedCost.totalCost < 0.01 ? '<0.01' : data.estimatedCost.totalCost.toFixed(2)}
                      </div>
                    ) : (
                      <div style={{ fontSize: '18px', fontWeight: 700, color: '#34d399' }}>
                        {'<'}¥0.01
                      </div>
                    )}
                    <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '10px', color: '#64748b', marginTop: '2px', justifyContent: 'flex-end' }}>
                      <SparklesIcon />
                      <span>{t.aiPowered}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div style={{
          padding: '10px 16px',
          backgroundColor: 'rgba(30, 41, 59, 0.3)',
          borderTop: '1px solid rgba(30, 41, 59, 0.5)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '4px',
          fontSize: '12px',
          color: '#64748b'
        }}>
          <span>{language === 'zh' ? '查看完整分析' : 'View Full Analysis'}</span>
          <ChevronRightIcon />
        </div>
      </div>
    );
  }
);

ShareCardCanvas.displayName = 'ShareCardCanvas';
export default ShareCardCanvas;
